worker_processes 1;
 
events { worker_connections 1024; }
 
http {

    upstream app {
      server frontend:5173;
    }

    upstream api {
      server api:8000;
    }

    upstream pgadmin {
      server pgadmin:80;
    }
 
    sendfile on;
    include mime.types;

    server {
      listen 8080;
      listen 8443 ssl;
      server_name pgadmin.notebook.com;

      ssl_certificate /keys/notebook.com.pem;
      ssl_certificate_key /keys/notebook.com-key.pem;

      location / {
          proxy_pass http://pgadmin;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
      }
    }

    server {
      listen 8080;
      listen 8443 ssl;
      server_name api.notebook.com;

      ssl_certificate /keys/notebook.com.pem;
      ssl_certificate_key /keys/notebook.com-key.pem;

      location / {
          proxy_pass http://api;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
      }
    }

    server {
      listen 8080;
      listen 8443 ssl;
      server_name notebook.com;

      ssl_certificate /keys/notebook.com.pem;
      ssl_certificate_key /keys/notebook.com-key.pem;

      location / {
          proxy_pass http://app;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
      }
    }
}
